name=Capteurs Arduino Library
version=0.0.1
author=boby15000 <boby15000@hotmail.com>
maintainer=boby15000 <boby15000@hotmail.com>
sentence=Bibliothèque de gestion de capteurs simplifié.
paragraph=Permet de faciliter l'écriture d'un sketch pour l'utilisation de capteur analogique tension.
category=Sensors Control
url=https://github.com/boby15000/Capteurs.git
architectures=*
includes=Capteurs.h